query Watchlist {
  watchlist {
    ...MovieCardFields
  }
}

mutation AddToWatchlist($movieId: Int!) {
  addToWatchlist(movieId: $movieId) {
    ...MovieCardFields
  }
}

mutation RemoveFromWatchlist($movieId: Int!) {
  removeFromWatchlist(movieId: $movieId) {
    ...MovieCardFields
  }
}

query Favorites {
  favorites {
    ...MovieCardFields
  }
}

mutation AddToFavorites($movieId: Int!) {
  addToFavorites(movieId: $movieId) {
    ...MovieCardFields
  }
}

mutation RemoveFromFavorites($movieId: Int!) {
  removeFromFavorites(movieId: $movieId) {
    ...MovieCardFields
  }
}
